# Generated by Django 4.2.4 on 2023-08-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_author_comment_dateadded_comment_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-dateAdded',)},
        ),
        migrations.AlterField(
            model_name='topic',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
