# Generated by Django 4.2.4 on 2023-08-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='tags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
