# Generated by Django 4.2.4 on 2023-08-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_like_options_like_created_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='followers',
        ),
    ]
