# Generated by Django 4.1.7 on 2023-03-08 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
