# Generated by Django 4.0.6 on 2023-03-04 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='topic',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
