# Generated by Django 4.0.6 on 2023-03-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_slug_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='these, are, random, tags', max_length=50),
            preserve_default=False,
        ),
    ]
