# Generated by Django 4.2.4 on 2023-08-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_topic_followers'),
        ('accounts', '0002_customuser_bio_customuser_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='followers', to='blog.topic'),
        ),
    ]
