# Generated by Django 4.2.4 on 2023-08-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profilePic',
        ),
    ]
